### ISSUE TITLE
issue with target_feature in Conditional Compilation Tags

### ISSUE THREAD

**Issue by lfreist** [BurntSushi/aho-corasick#141]
I am new to rust and have close to zero experience to the Conditional Compilation Tags in rust, so feel free to just close this issue if I am missing something.

As far as I understand Conditional Compiler Tags and specifically the `target_feature`-thing,  https://github.com/BurntSushi/aho-corasick/blob/cd400ad792d6888cc8fa4c1f9e2493b519961b3c/src/packed/vector.rs#L320 should be `#[cfg(all(target_arch = "x86_64", target_feature = "sse3"))]`, since at least `_mm_alignr_epi8` and `_mm_shuffle_epi8` used in the block require SSE3.

Similar, https://github.com/BurntSushi/aho-corasick/blob/cd400ad792d6888cc8fa4c1f9e2493b519961b3c/src/packed/vector.rs#L413 should be `#[cfg(all(target_arch = "x86_64", target_feature = "avx2"))]`.

Or am I missing something obvious?

**Comment by BurntSushi** [comment]
No that would be very bad. We specifically want to detect whether features like avx2 are enabled at runtime. We absolutely do not want to compile assuming avx2. If we did that, most users wouldn't benefit from it because they would 1) have to build their own software and 2) often install binaries built for them that are portable. That is, they work even when avx2 isn't available.

See: https://doc.rust-lang.org/std/arch/index.html#dynamic-cpu-feature-detection

**Comment by BurntSushi** [comment]
We do include sse2 because it is supposed to always be available for x86-64. But I'm practice, the OS can choose not to support the necessary registers during context switching. So we do require sse2 and avoid dealing with anything super exotic.

**Comment by lfreist** [comment]
This absolutely makes sense. Thank you for the insights!
