### ISSUE TITLE
Persist automaton to file such that it can be saved to disk and loaded back in memory

### ISSUE THREAD

**Issue by pombredanne** [BurntSushi/aho-corasick#22]
That would be an awesome addition (and side note: thank for you wonderful code and articles :bowing_man: )

**Comment by BurntSushi** [comment]
Thanks for the request, but I don't think it's a good fit for this crate. There is a gulf of difference in the implementation of disk serialized automata and in-memory automata. If someone wants a disk backed Aho-Corasick automaton, then they should just go out and do it in their own crate. I don't think they could reuse anything in this crate, assuming you want to support very large dictionaries.

**Comment by pombredanne** [comment]
@BurntSushi I am not suggesting to have in memory and on disk representation being the same.... instead something similar to what we do in https://github.com/WojciechMula/pyahocorasick e.g. something that can be saved and loaded (in this case a Python pickle, that comes with its load of issues)

**Comment by BurntSushi** [comment]
OK, I'm just plain confused at this point. When you said "fst-style", I assumed you were referring to the [fst crate](https://docs.rs/fst/0.3.0/fst/). The fst crate in particular has exactly one format: the on disk format. Searching the fst reads directly from the disk format (via a memory map) without deserializing into any intermediate in-memory fst.

However, your second comment here suggests that you just want to be able to serailize/deserialize aho-corasick to and from memory, probably by using serde and picking some binary format. Is that accurate? It's very different from your original fst-style request.

**Comment by pombredanne** [comment]
My bad for stating fst-style, which indeed would not make sense at all. 

> n particular, you are not requesting the capability to use the automaton directly from its serialized format without first deserializing it entirely into memory. Is that accurate? It's very different from your original fst-style request.

This is correct!

**Comment by pombredanne** [comment]
I updated the title accordingly... I confess that having just finished your 1.6B fst article this week end, my brain was fogged by  fst's ;)

**Comment by BurntSushi** [comment]
It looks like there might be some overlap between this ticket and #9, but I'll leave this open for now.

I doubt I'll work on this myself any time soon.

**Comment by Michael-F-Bryan** [comment]
It sounds like the OP is wanting to save a representation of the `AcAutomaton` to disk so later on you just need to deserialize this representation instead of regenerating it from scratch (assuming deserializing is a lot less expensive than rebuild the automaton). 

I imagine the easiest way to do this would be to implement `serde::Serialize` and `serde::Deserialize` for the automata using `serde_derive`. That way you can use the `serde_json` crate to dump an automaton as JSON and then reload it at a later point.

**Comment by BurntSushi** [comment]
I'm going to close this issue out. In particular, I believe my somewhat recently [`regex-automata`](https://docs.rs/regex-automata) crate is more suited to this use case, since it was explicitly designed to support cheap deserialization from an on-disk format. `regex-automata` supports the full power of regular expressions, so that should cover the use cases that Aho-Corasick targets. (With one unfortunate exception: I don't think `regex-automata` can easily handle the `find_overlapping` routine in this crate.) This way, I can have one crate that focuses on (de)serialization instead of re-inventing that logic elsewhere.

The downside to `regex-automata` is that it will take longer to compile large alternations of literals than Aho-Corasick does. But if you're serializing it, then presumably you can afford the extra compilation time. A critical piece to this is that deserialization is effectively free, because it will only do a constant amount of work, regardless of the size of your automaton.

**Comment by pombredanne** [comment]
@BurntSushi thank you for following up!
In my use case, finding all overlapping occurrences is kind of essential. But let me play with your  regex_automata first.

**Comment by BurntSushi** [comment]
Yes. Eventually regex-automata should support that via something like a RegexSet. But it is not implemented yet.

**Comment by pombredanne** [comment]
FWIW, yara rewrite in Rust by @plusvic does serialize this crate's automaton.

https://github.com/VirusTotal/yara-x/blob/9e6ef83adba0111be7e2e47906bfa201d451b741/lib/src/compiler/rules.rs#L109

**Comment by BurntSushi** [comment]
@pombredanne Huh? The comment you linked literally says it _doesn't_ serialize it:

```
    /// Aho-Corasick automaton containing the atoms extracted from the patterns.
    /// This allows to search for all the atoms in the scanned data at the same
    /// time in an efficient manner. The automaton is not serialized during when
    /// [`Rules::serialize`] is called, it needs to be wrapped in [`Option`] so
    /// that we can use `#[serde(skip)]` on it because [`AhoCorasick`] doesn't
    /// implement the [`Default`] trait.
```

**Comment by pombredanne** [comment]
@BurntSushi sorry, I posted too quickly.... @plusvic ... do you serialize the aho-corasick automaton at all in yara-x?

**Comment by BurntSushi** [comment]
Serialization can operate at multiple levels here. I alluded to this earlier, but to unpack this more explicitly:

1. One can want "zero-copy" (de)serialization, such that you have, say, a `AhoCorasick::from_bytes` constructor that takes a `&[u8]` and can execute a search without doing any copying of the transition table or allocations. This is what `regex-automata` provides. (I've mentioned `regex-automata` several times now, and it supports overlapping searches.) This is a very invasive change and it introduces the most coupling between crate internals and the public API. But it's also the nicest, fastest and most flexible option.
2. One can also want (de)serialization that doesn't quite give you what the zero-copy solution gives you, but its format would be aware of the internals and represent things efficiently in the serialized format. This would make (de)serialization relatively cheap, but still require copies/allocs. This provides _some_ degree of de-coupling between crate internals and the public API. That is, since there is an explicit (de)serialization step, if crate internals change, then it's possible to insert code to ensure the serialized format remains stable, possibly at some other cost. For example, it's probable that each of the Aho-Corasick automaton types in this crate (there are three) would each have their own serialization format.
3. A total de-coupling that crafts a (de)serialization format of a "logical" Aho-Corasick automaton that isn't at all tied to crate internals. This might require extra work at (de)serialization time, but provides a clean boundary. (And it isn't at all clear to me that this "extra work" is meaningful.) In contrast to (2) above, there would only be one serialization format.
4. Prioritize implementation simplicity above all else and just slap `derive(serde::Deserialize, serde::Serialize)` on everything until it "works." This introduces coupling to crate internals and possible huge sources of inefficiency.

(4) was suggested above and is absolutely not something I would ever pursue.

(1) would be amazing, but it is a monumental amount of work. To do it right, it's on the order of "rewrite the whole crate." Maybe not quite that much work, but not that far away from it.

My _guess_ is that the possible advantages of (2) over (3) are not worth it.

So (3) is probably what I would like to see. But the fact that it isn't (1) really bums me out, and is probably why I don't have much motivation to work on it. In particular, (1) unlocks very interesting use cases that I've seen deployed in real production systems. For example, pre-building an Aho-Corasick automaton at compile time, and then loading it at runtime without cost or any dynamic memory allocation (e.g., for an embedded system). This is how the `fst` crate is designed, for example. And is also how the DFAs in `regex-automata` work.
