### ISSUE TITLE
Is this crate thread safe?

### ISSUE THREAD

**Issue by rammy22** [BurntSushi/aho-corasick#47]
No mention of thread safety in the docs...

**Comment by BurntSushi** [comment]
Yes. I'm assuming you're new to Rust. Rust libraries that expose safe APIs often do not talk explicitly about thread safety because the compiler enforces it automatically. For example, the `AhoCorasick` type [implements both `Send` and `Sync`](https://docs.rs/aho-corasick/0.7.6/aho_corasick/struct.AhoCorasick.html#synthetic-implementations). `Send` means that an `AhoCorasick` value can safely be sent to another thread. `Sync` means that a _reference_ to an `AhoCorasick` value can safely be sent to another thread. The latter implies that it is safe to share a single `AhoCorasick` value across multiple threads simultaneously. The compiler will not let you screw this up.

**Comment by rammy22** [comment]
Good assumption :) Thank you for the answer!
