### ISSUE TITLE
next_state?

### ISSUE THREAD

**Issue by Triften** [BurntSushi/aho-corasick#66]
We were using (abusing?) v0.6's exposure of next_state, get_match, and has_match in order to run on streams (running over a chunk/frame at a time). Can this API be brought back?

**Comment by BurntSushi** [comment]
Unlikely. Consider using the [stream APIs](https://docs.rs/aho-corasick/0.7.13/aho_corasick/struct.AhoCorasick.html#method.stream_find_iter) or [`regex-automata`](https://docs.rs/regex-automata).

**Comment by Triften** [comment]
Thank you.

**Comment by BurntSushi** [comment]
No problem. And to be clear, if this were a simple matter of just adding some methods to the `AhoCorasick` type, then I wouldn't be opposed to such things. Being able to run an FSM from a low level like that is useful. Unfortunately, `AhoCorasick` is internally an enum over different possible representations of the FSM (principally, an NFA or a DFA). So if we exposed something like a `next_state` routine on `AhoCorasick`, then it would necessarily need to do switch over the different representations. This is quite a bit more expensive than you might otherwise expect, particularly in the DFA case, so it winds up creating a performance footgun.

I could be convinced to expose it anyway, with appropriate warnings. Otherwise, the only other approach I can think of would be to expose the internal NFA and DFA types, and _those_ could have routines like `next_state` defined on them.

**Comment by Triften** [comment]
Understandable.

Unfortunately, regex-automata only provides a bool rather than matching against multiple (potentially overlapping) patterns, otherwise it's nearly a drop in replacement for how we were using aho_corasick 0.6.

I am attempting to use the stream API, but it seems like the state machine resets for each call. (I'm passing a slice of u8s.) Is there a way to continue the search over a new slice?

**Comment by BurntSushi** [comment]
Ah yeah, `regex-automata 0.2` will support multiple patterns.

> I am attempting to use the stream API of 0.7, but it seems like the state machine resets for each call. (I'm passing a slice of u8s.) Is there a way to continue the search over a new slice?

Yeah, you'll have to provide your own implementation of `Read` that handles that I think. stream APIs are hard.

**Comment by ear7h** [comment]
I ran into a similar issue as well and thought I should share my solution. My requirements are slightly different than @Triften (passing `&[u8]`s is not required), I needed access to the output stream and I needed the non-matches to be returned ASAP. I should also mention that the input `Read` was a file opened with the `O_NONBLOCK` flag. 

I ended up using the `StreamChunkIter` structure but it tends to hold the buffer for too long so I had to modify `next` and the `Buffer::fill()`:

https://github.com/ear7h/wiki/blob/927e06d15b91229068487eeb2412a5e4d5b3ca42/lib/aho-corasick/src/ahocorasick.rs#L1478-L1488

https://github.com/ear7h/wiki/blob/927e06d15b91229068487eeb2412a5e4d5b3ca42/lib/aho-corasick/src/buffer.rs#L98

\* this modification was a quick hack, but I think the loop could continue and instead of using `?` it should only return the error if the buffer is empty. It's probably not a good idea to just suppress the error like that so maybe if the buffer gets some bytes it stores the error and returns it immediately in the next `fill()` call.

I'm not sure what the best approach would be to expose this functionality. My current thought is `StreamChunkIter` should be renamed `AhoCorasickStream` and it owns the underlying `Imp` and a `Read` so that the state can be preserved across method calls to a parent struct (you can't save `StreamChunkIter` and the referenced `AhoCorasick` in the same struct). To maintain the current functionality of a temporary `StreamChunkIter`, `AhoCorasickStream` can be deconstructed back into its parts `(AhoCorasick, Read)` (or maybe use the `Borrow`, but I'm not very familiar with it).
