### ISSUE TITLE
Motion to grant V1.0.0 status

### ISSUE THREAD

**Issue by rljacobson** [BurntSushi/aho-corasick#88]
I move that you version the current (or next) release as version 1.0.0. Recall the [Semantic Versioning spec](https://semver.org/):

> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
>
> 5. Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

Commits to this repo are now sparse. The last commit was 7 months ago. This is strong evidence of its API stability. Indeed, at this point, given the importance of this crate and how widespread its use is, changing the public API at any time is impractical anyway. The crate is *functionally* at v1. Officially bumping the version would just align the version number to its de facto use.

**Comment by BurntSushi** [comment]
Could you say specifically why releasing 1.0 would help you? I want to understand better the specific pressures pushing this to 1.0.

There are actually API changes planned. See #57 for example. And I don't know why you think API changes are impractical at this point. Could you please elaborate on that point?

**Comment by rljacobson** [comment]
I think I am arguing for a v1.0 for the same reason that semantic versioning is useful. Bumping to v1.0 does not preclude API changes. In fact, I argue that SemVer makes it easier on everyone when you make API breaking changes. I was intending to emphasize the "at any time" part, to say that as it stands, changes to the API require communication with the user base, and changing the API every couple of days would frustrate many of the crate's users. It is the idea of a _very unstable_ API that is impractical, not the idea of changing the API at all. SemVer makes it clear that any 1.* version maintains the same API. So any typo corrections, bug fixes, additions to documentation, or whatever else is improved that doesn't affect the API can be adopted with confidence knowing that changes to the client code won't be needed. When you are ready to land #57, you just bump the major version. That lets everyone know that they need to be aware of what has changed in the API and how it might affect their code. It also frees them from having to monitor _every_ release for changes that will break their code. 

There is a larger conversation about *why* knowing when the API changes is a good thing for users of the crate that I am barely touching on. Many bits have been spilled on the internet answering this question. ([Example](https://developer.okta.com/blog/2019/12/16/semantic-versioning).) For me personally, semantic versioning is really helpful in managing bit rot, which I deal with a lot in my own code. It also allows me to schedule *when* I pay the cost of upgrading a dependency. When I work on Project X, do I want to deal with, say, Nom's API changes right now, or is landing feature Y more important?

To be clear, I'm arguing for a positive major version number, not arguing for a specific path to it. You could make the current version be v1.0.0, or the commit with #57 be v1.0.0, or even some other commit.

**Comment by BurntSushi** [comment]
I think you might have a misunderstanding. Cargo treats any increment to the leftmost non-zero number as a breaking change. This is stricter than what semver says.

**Comment by BurntSushi** [comment]
Beyond what semver says, I personally generally treat 1.0 as meaning "this crate has reached maturity and is not expected to undergo any rapid API breaking changes." I am given the flexibility to do that by Cargo, because evem at 0.x, I can communicate breaking changes by releasing 0.(x+1).

**Comment by rljacobson** [comment]
> Cargo treats any increment to the leftmost non-zero number as a breaking change.

This is also my understanding. 

> This is stricter than what semver says.

I am not sure what you mean by stricter. If you mean that Cargo is more conservative than SemVer, then I don't think that's correct.

(But first a digression. SemVer says, after v1.0.0, if there is an API-breaking change, then the major version must be bumped. My only doubts are with the converse: is it true that if the major version is bumped, then there must have been an API-breaking change? Or equivalently, if there is not an API-breaking change, must the major version remain the same? I think it should, but... I don't see anything in the spec requiring it.)

Most relevant to this conversation is what happens at 0.* versions: The only way for the leftmost nonzero number to not be the major version number is when the major version is 0. But on 0.* versions *any* version bump can be a breaking change.

> ... even at 0.x, I can communicate breaking changes by releasing 0.(x+1).

No, at least not according to SemVer, in the sense that it is neither sufficient nor necessary:

1. SemVer does not require 0.(x+1) to be an API-breaking change. (Not sufficient.) 
2. A "patch" bump from 0.x.y to 0.x.(y+1) *may* be a breaking change. (Not necessary.)

Of course, SemVer is not BurnSushi's master. :) "SemVer was made for BurntSushi, not BurntSushi for SemVer," Developus 2:56.

> Beyond what semver says, I personally generally treat 1.0 as meaning "this crate has reached maturity and is not expected to undergo any rapid API breaking changes." 

I think that's fair. Do you feel that does not describe this crate? When was the last API-breaking change? How often do you anticipate making API-breaking changes in the future? Empirically, commits of any kind are sparse, with the last one over 5 months ago (not seven as I claimed before—oops), and API-breaking changes are even less frequent. The crate is widely deployed. It's 24<sup>th</sup> in the list of most downloads of all time on crates.io with ~52 million downloads. If this crate is not mature, then no crate is.

Keeping this crate at version 0.* is compatible with SemVer, I think, even if we are being hardline SemVer purists. But the SemVer spec also gives this guidance:

> **How do I know when to release 1.0.0?**
>
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by rljacobson** [comment]
Regarding my digression about the converse, it appears this issue has been discussed by the SemVer people in semver/semver#619. The conclusion was to keep the SemVer spec silent on whether or not a major version bump indicates an API change. 

Incidentally, that discussion demonstrates both the best kind and the worst kind of dialog on GitHub issues. It reminded me to thank you for your consistent positive influence on the tone and quality of the technical conversations I enjoy in various places online. 🤓

**Comment by BurntSushi** [comment]
> Incidentally, that discussion demonstrates both the best kind and the worst kind of dialog on GitHub issues. It reminded me to thank you for your consistent positive influence on the tone and quality of the technical conversations I enjoy in various places online. 

Thanks. And I'll say that while I appreciate a gentle nudge in the direction of releasing a 1.0, I think this issue has now spiraled into an interrogation into semver. I'd like to note the original question that I asked, and I'll add some emphasis this time:

> Could you say specifically why releasing 1.0 would help ***you***?

Your answer to that question hasn't really indicated how 1.0 would help _you_. Instead, what I see is a lawyerly presentation of a spec. You've made arguments that I am not ignorant of. Everything you've said I've heard a thousand times by denizens of the Internet, and I've reflected on all such points more than a few times over the years. But more to the point, I am not interested in debating semver in a vacuum. Because we don't live a vacuum. This is a **Rust** crate that uses Cargo to build itself. Therefore, there is more than semver going on here. Regardless of what you say, bumping the leftmost non-zero digit in the Rust ecosystem (even at 0.x or even 0.0.x) is a way to communicate a breaking change. This is an established convention. It works because Cargo treats, for example, 0.1 and 0.2 as incompatible.

> I am not sure what you mean by stricter. If you mean that Cargo is more conservative than SemVer, then I don't think that's correct.

It is stricter. semver says that "anything goes" in 0.x.y. Breaking changes can happen at any time. But Cargo considers 0.x.y and 0.(x+1).y as semver incompatible in _precisely_ the same way that Cargo considers x.y.z and (x+1).y.z semver incompatible. Thus, in an ecosystem built on top of Cargo, there is more strictness: if I need to make a breaking change, then I should release 0.(x+1).y even if I haven't released 1.0 yet. That is, I can opt into the _primary_ benefits of semver (***communicating*** API breaking changes) without having to release 1.0.

Your commentary on semver here, and specifically as it related to this crate, doesn't seem to account for this particular behavior of Cargo.

> is it true that if the major version is bumped, then there must have been an API-breaking change?

I think this is off topic for this specific issue. But no, I do not believe incrementing the leftmost non-zero digit of a version number must imply that a breaking change exists.

> I think that's fair. Do you feel that does not describe this crate? When was the last API-breaking change? How often do you anticipate making API-breaking changes in the future? Empirically, commits of any kind are sparse, with the last one over 5 months ago (not seven as I claimed before—oops), and API-breaking changes are even less frequent. The crate is widely deployed. It's 24th in the list of most downloads of all time on crates.io with ~52 million downloads. If this crate is not mature, then no crate is.

I anticipate at least one more round of breaking API changes, yes. Your sense of whether a time interval is long or not does not really match mine. It takes me a long time to do things these days, and I try to minimize context switching. That means some crates don't get much attention for long stretches of time, followed by a burst of activity. For example, I have been working on `regex-automata 0.2` for the last year or so, which is closely related to Aho-Corasick and has given me some ideas for API evolution. So yes, I do not feel like 1.0 is quite there yet. When I release 1.0, I want that to indicate that it represents an API that I'm committed to for a long period of time (on the order of "years"). If you look at the crates I've published, you'll notice that very few of them (only one I think) have gone to 2.0.0 or greater. This is no accident. That is a feature of my release strategy, not a bug. It means that if you're using a burntsushi crate at 1.0, then you're unlikely to experience _churn_, which is a real problem in the Rust ecosystem.

Also, the stats you use to indicate maturity are unconvincing to me. This crate is indeed widely deployed, but primarily indirectly. It number of [direct dependents](https://crates.io/crates/aho-corasick/reverse_dependencies) is considerably smaller. And many of its dependents are me. Thus, while the implementation is itself widely deployed, its **API** isn't. Relatively few are using the crate directly.

> But the SemVer spec also gives this guidance:

Yes. It's _guidance_. :-) Guidance based on an abstraction that does not precisely reflect its implementation in Cargo. And I disagree with it.

The bottom line here is that I was interested in how this was impacting _you_ personally. I am deeply uninterested in abstract arguments that don't touch reality in some way. For example, maybe you work at a company that prohibits the use of pre-1.0 libraries. (I've heard of such a thing.) Or maybe you're interested in using something from this crate in a public API of your crate and you want to know what the API evolution of this crate looks like. Or something similar. I don't know. That's kind of the thing I was looking for. Incidentally, I think this is also reflective of the commentary you've given. You are focused on semver _the spec_ as opposed to semver _the implementation in Cargo_. The latter is what I follow. Not the former. There's obviously a ton of similarity, but there's a couple crucial differences that have an impact on release strategy and the utility of 1.0.0.

**Comment by rljacobson** [comment]
> Your answer to that question hasn't really indicated how 1.0 would help you. Instead, what I see is a lawyerly presentation of a spec. 

Well, yes, I did give a lawyerly presentation, but in fairness, I also gave my own personal reasons:

> For me personally, semantic versioning is really helpful in managing bit rot, which I deal with a lot in my own code. It also allows me to schedule when I pay the cost of upgrading a dependency. When I work on Project X, do I want to deal with, say, Nom's API changes right now, or is landing feature Y more important?

It was only in subsequent conversation that you explain how your (Cargo's?) particular version of semver meets my described needs in your view. 

I think we've exhausted this topic, so I'm closing the issue. Thanks for the exchange!

**Comment by BurntSushi** [comment]
> Well, yes, I did give a lawyerly presentation, but in fairness, I also gave my own personal reasons

I see. But has this actually been a problem for you in practice in the Rust ecosystem? Or with this crate? That's what I meant. Every crate I've used knows about and employs Cargo's implementation of semver, rather than wildly releasing breaking changes in any version pre-1.0. I was more interested in the actual problems you have experienced.
