### ISSUE TITLE
Add support for async/non-blocking

### ISSUE THREAD

**Issue by jakajancar** [BurntSushi/aho-corasick#95]
Unless I'm missing something, `aho-corasick` either requires the entire haystack, or a `Read` on which it blocks.

It would be nice if you could feed it bytes as they come in.

**Comment by BurntSushi** [comment]
The Read trait supports that.

I will not be adding async support without a very compelling and detailed justification for it. If you can provide that, we can reopen this issue.

**Comment by BurntSushi** [comment]
You haven't described your problem in enough detail for me to be able to answer you.

async seems like a red herring.

It sounds like you want a push API, but this crate only exposes a pull API. If you want a push API you'll probably need to build it yourself using regex-automata.

**Comment by BurntSushi** [comment]
Like I said, I don't see this happening without a very detailed investigation. This crate is primarily about text search, which is a CPU bound operation. There's only a tiny little sliver of API that has anything to do with I/O, and that's a convenience function for searching std::io::Read because it's a low hanging fruit.

**Comment by BurntSushi** [comment]
I would rather work to expose APIs that permit callers to implement any necessary I/O glue instead of providing it in this crate.
